// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIjgf_rMzlKfMpFSyvpo2gvIShFOJ7sXs',
    appId: '1:40944718112:web:c0a35668bac67ce9ef4745',
    messagingSenderId: '40944718112',
    projectId: 'task-firebaseproject',
    authDomain: 'task-firebaseproject.firebaseapp.com',
    storageBucket: 'task-firebaseproject.appspot.com',
    measurementId: 'G-6FW8H5QTX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdtaVzPgNVBaySbZ9GNCCz20iT_2TqS1Y',
    appId: '1:40944718112:android:638e4e9ce208d86aef4745',
    messagingSenderId: '40944718112',
    projectId: 'task-firebaseproject',
    storageBucket: 'task-firebaseproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCflugGovRmNE7FF72JuV0y5y54xWya_5s',
    appId: '1:40944718112:ios:4a3091f58d7a06efef4745',
    messagingSenderId: '40944718112',
    projectId: 'task-firebaseproject',
    storageBucket: 'task-firebaseproject.appspot.com',
    iosBundleId: 'com.firebaselocal.local.api5Firebase',
  );
}
